### ISSUE TITLE
NullPointerException on click villager

### ISSUE THREAD

**Issue by leviem1** [leviem1/MobPortals#5]
**Describe the bug**
A clear and concise description of what the bug is

**To Reproduce**
Unsure the cause

**Expected behavior**
Command or clicking on mobs should teleport the player

**Screenshots**
Not applicable

**Version information:**
 - Vanilla version: 1.16.1
 - Server version: paper-130
 - Plugin version: v1.0.0

**Additional context**
```
Caused by: java.lang.NullPointerException
        at shadow.io.papermc.paperlib.features.asyncchunks.AsyncChunksPaper_15.getChunkAtAsync(AsyncChunksPaper_15.java:11) ~[?:?]
        at shadow.io.papermc.paperlib.environments.Environment.getChunkAtAsync(Environment.java:84) ~[?:?]
        at shadow.io.papermc.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:133) ~[?:?]
        at shadow.io.papermc.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:97) ~[?:?]
        at com.snowypeaksystems.mobportals.MobPortals.warpPlayer(MobPortals.java:128) ~[?:?]
        at com.snowypeaksystems.mobportals.MobPortals.warpPlayer(MobPortals.java:121) ~[?:?]
        at com.snowypeaksystems.mobportals.CommandListener.warp(CommandListener.java:203) ~[?:?]
        at com.snowypeaksystems.mobportals.CommandListener.onCommand(CommandListener.java:87) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-131]
```

**Comment by leviem1** [comment]
Will see how this goes with latest version

**Comment by leviem1** [comment]
Caused by an issue where Multiverse worlds are not present at load time, causing the world to appear "null". Will implement a list of warps to try again after the server starts "ticking" if they weren't found initially.
